export const EventEnum = {
  INI: 'Inicializacion',
  LLEG_MOST: 'Llegada mostrador',
  LLEG_AUTO: 'Llegada autoservicio',
  LLEG_ONLINE: 'Llegada online',
  LLEG_LLEVAR: 'Llegada para llevar',
  LLEG_DELI: 'Llegada delivery',
  FIN_MOST_1: 'Fin atencion mostrador 1',
  FIN_MOST_2: 'Fin atencion mostrador 2',
  FIN_MOST_3: 'Fin atencion mostrador 3',
  FIN_MOST_4: 'Fin atencion mostrador 4',
  FIN_MOST_5: 'Fin atencion mostrador 5',
  FIN_AUTO_1: 'Fin atencion autoservicio 1',
  FIN_AUTO_2: 'Fin atencion autoservicio 2',
  FIN_AUTO_3: 'Fin atencion autoservicio 3',
  FIN_ONLINE_1: 'Fin atencion online 1',
  FIN_ONLINE_2: 'Fin atencion online 2',
  FIN_ONLINE_3: 'Fin atencion online 3',
  FIN_LLEVAR_1: 'Fin atencion para llevar 1',
  FIN_LLEVAR_2: 'Fin atencion para llevar 2',
  FIN_DELI_1: 'Fin atencion delivery 1',
  FIN_DELI_2: 'Fin atencion delivery 2',
  FIN_DELI_3: 'Fin atencion delivery 3',
} as const;
