export const EventEnum = {
  INI: 'Inicialización',
  LLEG_MOST: 'Llegada mostrador',
  LLEG_AUTO: 'Llegada autoservicio',
  LLEG_ONLINE: 'Llegada online',
  LLEG_LLEVAR: 'Llegada para llevar',
  LLEG_DELI: 'Llegada delivery',
  CORTE_ELEC: 'Corte de electricidad',
  FIN_MOST_1: 'Fin atención mostrador 1',
  FIN_MOST_2: 'Fin atención mostrador 2',
  FIN_MOST_3: 'Fin atención mostrador 3',
  FIN_MOST_4: 'Fin atención mostrador 4',
  FIN_MOST_5: 'Fin atención mostrador 5',
  FIN_AUTO_1: 'Fin atención autoservicio 1',
  FIN_AUTO_2: 'Fin atención autoservicio 2',
  FIN_AUTO_3: 'Fin atención autoservicio 3',
  FIN_ONLINE_1: 'Fin atención online 1',
  FIN_ONLINE_2: 'Fin atención online 2',
  FIN_ONLINE_3: 'Fin atención online 3',
  FIN_LLEVAR_1: 'Fin atención para llevar 1',
  FIN_LLEVAR_2: 'Fin atención para llevar 2',
  FIN_DELI_1: 'Fin atención delivery 1',
  FIN_DELI_2: 'Fin atención delivery 2',
  FIN_DELI_3: 'Fin atención delivery 3',
  FIN_POSTRE: 'Fin atención postre',
  FIN_CORTE_ELEC: 'Fin corte de electricidad',
} as const;
