export const StateEnum = {
  LIBRE: 'libre',
  OCUPADO: 'ocupado',
  ESP_ATE_MOST: 'EAM',
  ESP_ATE_AUTO: 'EAA',
  ESP_ATE_ONLINE: 'EAO',
  ESP_ATE_LLEVAR: 'EAL',
  ESP_ATE_DELI: 'EAD',
  SIE_ATE_MOST_1: 'SAM (1)',
  SIE_ATE_MOST_2: 'SAM (2)',
  SIE_ATE_MOST_3: 'SAM (3)',
  SIE_ATE_MOST_4: 'SAM (4)',
  SIE_ATE_MOST_5: 'SAM (5)',
  SIE_ATE_AUTO_1: 'SAA (1)',
  SIE_ATE_AUTO_2: 'SAA (2)',
  SIE_ATE_AUTO_3: 'SAA (3)',
  SIE_ATE_ONLINE_1: 'SAO (1)',
  SIE_ATE_ONLINE_2: 'SAO (2)',
  SIE_ATE_ONLINE_3: 'SAO (3)',
  SIE_ATE_LLEVAR_1: 'SAL (1)',
  SIE_ATE_LLEVAR_2: 'SAL (2)',
  SIE_ATE_DELI_1: 'SAD (1)',
  SIE_ATE_DELI_2: 'SAD (2)',
  SIE_ATE_DELI_3: 'SAD (3)',
} as const;
